name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check the existence of built JavaScript action
        shell: bash
        run: |
          if [[ -e ./action/lib/main.js ]]; then
            exit 0
          fi
    
          msg=$(tr '\n' '%0A' << 'EOF'
            This TypeScript action cannot be used before building within Node.js environment.
            Maybe you are currently using non-tagging branches, for example, the "@master".
            Only v* branches have built JavaScript action file.
            If you would like to test unreleased changes, please refer to the CI workflows in
            our repository: https://github.com/jurplel/install-qt-action .
            Exiting
          EOF
          )
          echo "::error :$msg"
    
          exit 1
