name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check the existence of built JavaScript action
        shell: python
        run: |
          from pathlib import Path
    
          if Path("./action/lib/main.js").exists():
              exit(0)
    
          lines = (
            'This TypeScript action cannot be used before building within Node.js environment.',
            'Maybe you are currently using non-tagging branches, for example, the "master" branch.',
            'Only v* branches have built JavaScript action file.',
            'If you would like to test unreleased changes, please refer to the CI workflows in',
            'our repository: https://github.com/jurplel/install-qt-action .',
            'Exiting',
          )
          message = '%0A'.join(lines)
          print(f"::error file=action.yml,title=Action not built::{message}")
    
          exit(1)
